Parameters:
  NetworkStackName:
    Description: Name of the base stack with all infra resources
    Type: String
    Default: vpc
  InstanceType:
    Type: String
    Default: kafka.t3.small
Description: MSK Cluster with all properties
Resources:
  TestCluster:
    Type: 'AWS::MSK::Cluster'
    Properties:
      ClusterName: Properties
      KafkaVersion: 2.8.0
      NumberOfBrokerNodes: 3
      EnhancedMonitoring: PER_BROKER
      ConnectivityInfo:
        PublicAccess:
           Type: "SERVICE_PROVIDED_EIPS"
      ClientAuthentication:
             Sasl:
               Iam:
                   Enabled: True
                      
      Tags:
           Environment: Test
           Owner: QATeam
      BrokerNodeGroupInfo:
        BrokerAZDistribution: DEFAULT
        InstanceType: !Ref InstanceType
        SecurityGroups:
          - 'Fn::ImportValue':
              'Fn::Sub': '${NetworkStackName}-SecurityGroupID'
        StorageInfo:
          EBSStorageInfo:
            VolumeSize: 50
        ClientSubnets:
          - 'Fn::ImportValue':
              'Fn::Sub': '${NetworkStackName}-PublicSubnet1ID'
          - 'Fn::ImportValue':
              'Fn::Sub': '${NetworkStackName}-PublicSubnet2ID'
          - 'Fn::ImportValue':
              'Fn::Sub': '${NetworkStackName}-PublicSubnet3ID'

